ITEM_TABLE = {
    "A": {
        "price": 50,
        "offer_type": "PRICE_REDUCT_MULTI",
        "offer_price": 130,
        "offer_quantity": 3,
        "offer_type_1": "PRICE_REDUCT_MULTI",
        "offer_price_1": 200,
        "offer_quantity_1": 5,
    },
    "B": {
        "price": 30,
        "offer_type": "PRICE_REDUCT_SINGLE",
        "offer_price": 45,
        "offer_quantity": 2,
    },
    "C": {
        "price": 20,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "D": {
        "price": 15,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "E": {
        "price": 40,
        "offer_type": "BOGOO",
        "bogoo_item": "B",
        "offer_price": 0,
        "offer_quantity": 2,
    },
    "F": {
        "price": 10,
        "offer_type": "BOGO",
        "offer_price": 0,
        "offer_quantity": 2,
    },
    "G": {
        "price": 20,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "H": {
        "price": 10,
        "offer_type": "PRICE_REDUCT_MULTI",
        "offer_price": 45,
        "offer_quantity": 5,
        "offer_type_1": "PRICE_REDUCT_MULTI",
        "offer_price_1": 80,
        "offer_quantity_1": 10,
    },
    "I": {
        "price": 35,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "J": {
        "price": 60,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "K": {
        "price": 70,
        "offer_type": "PRICE_REDUCT_SINGLE",
        "offer_price": 120,
        "offer_quantity": 2,
    },
    "L": {
        "price": 90,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "M": {
        "price": 15,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "N": {
        "price": 40,
        "offer_type": "BOGOO",
        "bogoo_item": "M",
        "offer_price": 0,
        "offer_quantity": 3,
    },
    "O": {
        "price": 10,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "P": {
        "price": 50,
        "offer_type": "PRICE_REDUCT_SINGLE",
        "offer_price": 200,
        "offer_quantity": 5,
    },
    "Q": {
        "price": 30,
        "offer_type": "PRICE_REDUCT_SINGLE",
        "offer_price": 80,
        "offer_quantity": 3,
    },
    "R": {
        "price": 50,
        "offer_type": "BOGOO",
        "bogoo_item": "Q",
        "offer_price": 0,
        "offer_quantity": 3,
    },
    "S": {
        "price": 20,
        "offer_type": "GROUP_BUY",
        "offer_price": 45,
        "offer_quantity": 3,
        "group_buy_items": ["S", "T", "X", "Y", "Z"],
    },
    "T": {
        "price": 20,
        "offer_type": "GROUP_BUY",
        "offer_price": 45,
        "offer_quantity": 3,
        "group_buy_items": ["S", "T", "X", "Y", "Z"],
    },
    "U": {
        "price": 40,
        "offer_type": "BOGO",
        "offer_price": 0,
        "offer_quantity": 3,
    },
    "V": {
        "price": 50,
        "offer_type": "PRICE_REDUCT_MULTI",
        "offer_price": 90,
        "offer_quantity": 2,
        "offer_type_1": "PRICE_REDUCT_MULTI",
        "offer_price_1": 130,
        "offer_quantity_1": 3,
    },
    "W": {
        "price": 20,
        "offer_type": "",
        "offer_price": 0,
        "offer_quantity": 0,
    },
    "X": {
        "price": 17,
        "offer_type": "GROUP_BUY",
        "offer_price": 45,
        "offer_quantity": 3,
        "group_buy_items": ["S", "T", "X", "Y", "Z"],
    },
    "Y": {
        "price": 20,
        "offer_type": "GROUP_BUY",
        "offer_price": 45,
        "offer_quantity": 3,
        "group_buy_items": ["S", "T", "X", "Y", "Z"],
    },
    "Z": {
        "price": 21,
        "offer_type": "GROUP_BUY",
        "offer_price": 45,
        "offer_quantity": 3,
        "group_buy_items": ["S", "T", "X", "Y", "Z"],
    },
}
